### 회원가입

POST http://localhost:8080/test-reissue
Content-Type: application/json



### 로그인

GET http://localhost:8080/profile/changed
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ0eXBlIjoiYWNjZXNzX3Rva2VuIiwidXNlcm5hbWUiOiJhZG1pbiIsInJvbGUiOiJVU0VSIiwiaWF0IjoxNzQwODg3NTI3LCJleHAiOjE3NDA5NzM5Mjd9.i3ITzjRkt7aKC9ycdETyCr1zymdo_9QJdKcOM63dTM8
Content-Type: application/json


### 사용자 페이지

GET http://localhost:8080/member


### 관리자 페이지

GET http://localhost:8080/admin


### 메인 페이지

GET http://localhost:8080
